### ISSUE TITLE
The generated DDL SQL for entities with foreign keys causes duplicated indexes with the same name

### ISSUE THREAD

**Issue by MichaelSteinecke** [bubibubi/EntityFrameworkCore.Jet#113]
Hello,
with the same model as from Issue110, there is another issue. When running a database creation or migration from the scaffolded model, the same index is generated twice with the same name and fails eventuelly.

As far as I understand Access DBMS correctly, Access in contrast to SQL Standard will create an index together with a the FK constrains, unless 'NO INDEX' is explicitly specified.

CONSTRAINT name {PRIMARY KEY (primary1[, primary2 [, …]]) | UNIQUE (unique1[, unique2 [, …]]) | NOT NULL (notnull1[, notnull2 [, …]]) | FOREIGN KEY [NO INDEX] (ref1[, ref2 [, …]]) REFERENCES foreigntable [(foreignfield1 [, foreignfield2 [, …]])] [ON UPDATE CASCADE | SET NULL] [ON DELETE CASCADE | SET NULL]}

To prevent the automatic creation of indexes for foreign keys, the modifier NO INDEX can be used. This form of foreign key definition should be used only in cases where the resulting index values would be frequently duplicated. Where the values in a foreign key index are frequently duplicated, using an index can be less efficient than simply performing a table scan. Maintaining this type of index, with rows inserted and deleted from the table, degrades performance and does not provide any benefit.

[Source](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/constraint-clause-microsoft-access-sql)
Repo including example model:
[Issue113.zip](https://github.com/bubibubi/EntityFrameworkCore.Jet/files/7726698/Issue113.zip)

The model is scaffolded with `dotnet ef dbcontext scaffold "Data Source=JetDatabaseModelFactoryTest.mdb" EntityFrameworkCore.Jet --project "Issue113" --startup-project "Issue113" --output-dir "Models" --context-dir "Context" --context "Context"`

**Comment by lauxjpn** [comment]
The simplest fix for us to implement is probably to not scaffold indexes with the same name as existing constraints.
I'll look into it.
