### ISSUE TITLE
Error when connecting to Access database (*.mdb)

### ISSUE THREAD

**Issue by BrandonStudio** [bubibubi/EntityFrameworkCore.Jet#124]
> Microsoft Access database engine could not find "MSysAccessStorage"

Is this means that my database file has something wrong? What can I do then?

Why is it trying to find MSysAccessStorage?

**Comment by lauxjpn** [comment]
@BrandonStudio Is this an exception? If so, please post the full exception, including the stack trace.
Also, please provide us with some context, e.g. about when this issue appearing.

**Comment by bubibubi** [comment]
I think that is related to _Dual_ table simulation.
You can try to create MSysAccessStorage with one row or create a new table and change the configuration.

**Comment by lauxjpn** [comment]
@BrandonStudio We need (at least part of) the stack trace, so we know _where_ in our code the exception is being thrown. This is necessary so that we know when we have reproduced the issue.

Also, please confirm that this issue happens when _connecting_ to the database (meaning, it is the connection process that fails, not the query execution process).

Once we got the requested information from your, we will take a look at it.

Thanks!

**Comment by lauxjpn** [comment]
@BrandonStudio I am aware about the nature of the issue from you first 3 posts.

We still need the stack trace:

To show the `[external code]` section, refer to [What does "external code" in the call stack mean?](https://stackoverflow.com/a/31044557/2618319) (basically, click "Show External Code").

The full stack trace should also be available as a property of the `Exception` object (see [Exception.StackTrace Property](https://docs.microsoft.com/en-us/dotnet/api/system.exception.stacktrace?view=net-6.0)). You could copy its value from the debug/variable window or from the exception popup in VS.

Another way is to catch the exception and to just log or output it. This would call `Exception.ToString()`, which would return the exception type, its message and the stack trace:

```c#
try
{
    // Code that throws the exception.
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```

By the looks of the two lines of source code you provided in your screenshot, it is likely that the exception is thrown when executing a query, not when connecting to the database, but we will wait for the strack trace to confirm this.

---

Also, please do not provide screenshots unless there is no other way. Always copy and past text if possible.

**Comment by bubibubi** [comment]
**Any** queries uses **Dual** table simulation.
As far as I remember is a static member and you can change it with a table with a single record.
There should be a comment about this setting.
