### ISSUE TITLE
Any() not supported

### ISSUE THREAD

**Issue by techcap** [bubibubi/EntityFrameworkCore.Jet#16]
Any() from DbSet<> does not be supported.

It occurs the exception.
```
+		$exception	{"The Microsoft Jet database engine cannot find the input table or query 'MSysAccessStorage'.  Make sure it exists and that its name is spelled correctly."}	System.Data.OleDb.OleDbException
```

FirstOrDefault() works properly.

**Comment by bubibubi** [comment]
Are you using an mdb file or accdb file?

**Comment by techcap** [comment]
I used mdb file.

**Comment by bubibubi** [comment]
Could you please check this?
https://github.com/bubibubi/JetEntityFrameworkProvider/blob/master/docs/mdb_or_accdb_setup.md
I still haven't add this documentation to the new provider

**Comment by techcap** [comment]
Should I compile the source code? Using nuget package, I cannot find JetConnection.DUAL property.

**Comment by bubibubi** [comment]
The right class is JetConfiguration
Here you can find the right solution.
https://github.com/bubibubi/EntityFrameworkCore.Jet/wiki/Connection-configuration

**Comment by techcap** [comment]
After adding the code below, error message is changed.

```
JetConfiguration.DUAL = JetConfiguration.DUALForMdb;
```

Error message
```
+		$exception	{"Record(s) cannot be read; no read permission on 'MSysRelationships'."}	System.Data.OleDb.OleDbException
```

**Comment by bubibubi** [comment]
Please check **Note for mdb users and DualForMdb** section of the documentation

**Comment by techcap** [comment]
It works. I added some code on the DbContext static constructor for using Any() instead of FirstOrDefault().
But it looks not good idea.

Anyway, it's my code.

```
        static MyDbContext()
        {
            JetConfiguration.DUAL = "Dual";

            using (var context = new MyDbContext())
            {
                try
                {
                    var result = context.Database.ExecuteSqlCommand("SELECT * FROM Dual");
                }
                catch
                {
                    try
                    {
                        context.Database.ExecuteSqlCommand(@"
                            CREATE TABLE Dual (id COUNTER CONSTRAINT pkey PRIMARY KEY);
                            INSERT INTO Dual(id) VALUES(1);
                            ALTER TABLE Dual ADD CONSTRAINT DualTableConstraint CHECK((SELECT Count(*) FROM Dual) = 1);
                        ");
                    }
                    catch { }
                }
            }
        }
```
