### ISSUE TITLE
Update to 2.1

### ISSUE THREAD

**Issue by gojanpaolo** [bubibubi/EntityFrameworkCore.Jet#20]
It would be nice if we could bump the minor version to 2.1 to match the latest EF Core version.
Please let me know if you need help on this. :)

**Comment by bubibubi** [comment]
Thanks for the offer!!!
I'm already working on it. There are some issues on tests but within a week I will be probably able to release a preliminary version.

**Comment by gojanpaolo** [comment]
Awesome! Thank you :)

**Comment by bubibubi** [comment]
There are tons of non working tests but the provider seems to work.
Lazy load and Group by works.
It's still in preview so to download from nuget you need to enable previews.

**Comment by liuyu81** [comment]
Looking forward to the full release of 2.1

**Comment by techcap** [comment]
Will it be supported .net core also?

**Comment by bubibubi** [comment]
Actually is not possible.
To access to a Microsoft Access database we need to use OleDb and the Microsoft Access OleDb provider. They are both not ported to .Net Core.
