### ISSUE TITLE
EnsureDeleted doesn't work

### ISSUE THREAD

**Issue by gojanpaolo** [bubibubi/EntityFrameworkCore.Jet#21]
.NET Framework 4.7.2 Console App
install-package entityframeworkcore.jet -version 2.0.0

    using EntityFrameworkCore.Jet;
    using Microsoft.EntityFrameworkCore;

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new Context())
            {
                ctx.Database.EnsureCreated();
            }

            using (var ctx = new Context())
            {
                ctx.Database.EnsureDeleted();
            }
        }
        public class Context : DbContext
        {
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseJet("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=db.mdb;");
            }
        }
    }

**Comment by bubibubi** [comment]
I try it (with version 2.1.0-preview3) and it works.
What is exactly the error you are receiving?

**Comment by gojanpaolo** [comment]
Still doesn't work with 2.1.0-preview3.
There's no error/exception. It just doesn't delete the database.

**Comment by bubibubi** [comment]
The problem is related to the latest ; on the connection string. I need to fix the connection string parser. Meanwhile you can remove it and then it should work

**Comment by gojanpaolo** [comment]
Ah. It never occured to me to that it was the connection string. Thank you! :D

**Comment by bubibubi** [comment]
My fault. I'm not able to write regular expressions... Every time there is
something that does not work.
I use it to retrieve the name of the file to delete...


Il gio 5 lug 2018, 19:37 Jan Paolo Go <notifications@github.com> ha scritto:
