### ISSUE TITLE
Update-Database always wants to create new Database in Code First

### ISSUE THREAD

**Issue by TelcoPhil** [bubibubi/EntityFrameworkCore.Jet#26]
Hi Bubibubi,

this may be a problem of me not understanding how it works but here's my problem:
I have a Code-First scenario with a couple of DBsets etc. First generation via Add-Migration + Update-Database works like a charm, but if I change the code, add another migration and then run Update-Database again it fails, because it wants to create the Database again, not only apply the changes. Am i missing something or is that a bug? (I have -StartupProject and -Project parmeters set)
Thank you for the great work!
Best, phil

**Comment by MarcinWerra** [comment]
Phil, I had the same problem.
I noticed that I was creating a path to the database file in quotes.

`string myConnectionString = string.Format("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"{0}\";", pathToFile);`

Of course, this is correct. However, in the **System.Data.Jet.JetConnection.DatabaseExists** function there is a small error by which paths containing quotes are always considered non-existent.
The solution was to write the paths without the quotes.

`string myConnectionString = string.Format("Provider=Microsoft.Jet.OLEDB.4.0;Data Source={0};", pathToFile);`

Bubibubi in the **System.Data.Jet.JetConnection.DatabaseExists** function, you would have to cut quotes from the beginning and end of the path before checking if the path exists.
Maybe this way:

```
bool System.Data.Jet.JetConnection.DatabaseExists(string connectionString)
{
  string fileName = JetStoreDatabaseHandling.ExtractFileNameFromConnectionString(connectionString);
  if (string.IsNullOrWhiteSpace(fileName))
    throw new Exception("Cannot retrieve file name from connection string");

  **fileName = fileName.Trim('"');**
  
  return System.IO.File.Exists(fileName);
}
```

Best regards and thank you for this great component.

**Comment by bubibubi** [comment]
Thanks to you for the suggested fix!!!
