### ISSUE TITLE
System.Data.OleDb.OleDbException can not find database file

### ISSUE THREAD

**Issue by sofu456** [bubibubi/EntityFrameworkCore.Jet#36]
i use the entityframework but it does not create the database file of access . should it create file by myself before i use the framework.thank you.

**Comment by lauxjpn** [comment]
There are currently some glitches in the code base surrounding database creation.
How does your database creation code and connection string look like?
What is the exception (including stack trace etc.) you are getting?

**Comment by bubibubi** [comment]
To create the database the driver uses ADOX that is a 32 bit library.
If you don't want to compile the driver and the application using 32 bit, you can create the database before.

**Comment by sofu456** [comment]
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseJet("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.\\" + 
                DateTime.Now.ToString("yyyyMMdd") + ".mdb;Driver={MicrosoftAccessDriver(*.mdb)};");
        }

config like this. is the office 365 does not supported by the library?

**Comment by lauxjpn** [comment]
> To create the database the driver uses ADOX that is a 32 bit library.
If you don't want to compile the driver and the application using 32 bit, you can create the database before.

As @bubibubi said, database creation depends on the `ADOX.Catalog` COM component, which is 32 bit. So you should ensure, that your application is being run as 32 bit. The easiest way to do this is to check the result of `Environment.Is64BitProcess`. The result needs to be `false`, for the creation methods to work:

```c#
Debug.Assert(!Environment.Is64BitProcess); // <-- check target platform

using (var context = new Context())
{
    context.Database.EnsureDeleted();
    context.Database.EnsureCreated(); // <-- create new database

    // To your stuff here.
}
```

If the result is `true`, you need to change the platform target of the project to `x86`. You can do this in the Visual Studio GUI, or by editing the `.csproj` file and adding/changing the following line:

```xml
<PropertyGroup>
    <PlatformTarget>x86</PlatformTarget>
</PropertyGroup>
```

**Comment by lauxjpn** [comment]
> There are currently some glitches in the code base surrounding database creation.

Talking about a problem with our database creation code in general here, the current code base uses an empty connection that uses `JetConfiguration.OleDbDefaultProvider` which is set to `Microsoft.ACE.OLEDB.15.0`, which is just an arbitrary version (and is not installed on my own machine for example, that uses Office 365).
Instead, it should use the provider specified in the `UseJet()` call.

We might also want to add some kind of Jet version option, that can be used in database creation call to specify the database compatibility.
