### ISSUE TITLE
Scaffold-DbContext : Exception calling "Start" with "1" argument(s): "The system cannot find the file specified

### ISSUE THREAD

**Issue by olakusibe** [bubibubi/EntityFrameworkCore.Jet#38]
I keep getting this error while trying to scaffold from an existing mdb file, I have checked and confirmed that `ACEOLEDB 12` in installed also I target `.NET Framework 4.7.2` and package are `EntityFrameworkCore.Jet 2.2.0 ` and `Microsoft.EntityFrameworkCore.Tools 2.2.4`

`Scaffold-DbContext : Exception calling "Start" with "1" argument(s): "The system cannot find the file specified"`
`At line:1 char:1`
`+ Scaffold-DbContext -Connection "Provider=Microsoft.ACE.OLEDB.12.0;Dat ...`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
    `+ CategoryInfo          : NotSpecified: (:) [Scaffold-DbContext], MethodInvocationException`
`    + FullyQualifiedErrorId : Win32Exception,Scaffold-DbContext`
 

Is there anything I am missing or doing wrong?

Also I tried the same setup targeting `.NET Core 2.2` but get a different error
`'The application to execute does not exist:` `'C:\Users\olash\source\repos\Foltoy.Legacy.RecentBanker\packages\Microsoft.EntityFrameworkCore.Tools.3.1.1\tools\netcoreapp2.0\any\ef.dll'`

**Comment by lauxjpn** [comment]
Please post us the commands you tried to execute.

**Comment by olakusibe** [comment]
via PMC
`Scaffold-DbContext -Connection "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\RecentBanker_MFB\RDBMS\CDB2.MDB;Jet OLEDB:Database Password=mysecretpassword;" -Provider EntityFrameworkCore.Jet -OutputDir Models -verbose`

**Comment by lauxjpn** [comment]
Do you get the same error when running it via the command line as:

`dotnet ef dbcontext scaffold "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\RecentBanker_MFB\RDBMS\CDB2.MDB;Jet OLEDB:Database Password=mysecretpassword;" EntityFrameworkCore.Jet -o Models -verbose`

How does the full verbose output look like?

**Comment by olakusibe** [comment]
Yet to try running it through the command line .

Although, I setup a fresh project and set it to compile as `x86`, and is given another error of "file cannot be opened by older application" so I tried using `Microsoft.ACE.OLEDB.4.0`, but that also is given an error `The 'Microsoft.ACE.OLEDB.4.0' provider is not registered on the local machine.`

Its obvious the mdb file version is old, and I can seems to find ACOLEDB 4.0 driver online.

SO far, I have spent to much time getting it to work, so I am trying a different path of using ADO in .NET Standard Library and port it into .NET Core and build from there

Thanks

**Comment by lauxjpn** [comment]
The older 4.0 driver is `Microsoft.Jet.OLEDB.4.0` (not `ACE`).
