### ISSUE TITLE
Implement parallel support for ODBC and OLE DB

### ISSUE THREAD

**Issue by lauxjpn** [bubibubi/EntityFrameworkCore.Jet#45]
Continues the discussion around this feature from #43.

**Comment by lauxjpn** [comment]
For all advanced statements (like `CREATE VIEW` or `CREATE PROCEDURE`) to work with ODBC, `ExtendedAnsiSQL=1` has do be added to the connection string (see [Using the ExtendedAnsiSQL Connection String Attribute (Access Driver)](https://docs.microsoft.com/en-us/sql/odbc/microsoft/using-the-extendedansisql-connection-string-attribute-access-driver?view=sql-server-ver15) for further details).

We should do this implicitly in EFCore.Jet, so that nobody has to worry about it. In case anybody complains about it in the future for some reason, we can always add an option to give users the option to disable it.

I also had to switch the identifier character from `[identifier]` (square brackets) to `` `identifier` `` (backticks) because ODBC complaint about the square brackets when used for the newly supported ODBC 4.0 statements (like `CREATE VIEW`). The backtick is the official identifier character for ODBC and works for OLE DB and in Access as well.

**Comment by lauxjpn** [comment]
I am going to add support for automatic provider/driver detection, so that just specifying a database name will use the newest installed database provider/driver.

**Comment by lauxjpn** [comment]
In the future, we should consider refactoring the ODBC/OLE DB conditionals into their own self-contained classes, and ship them as `EntityFrameworkCore.Jet.Odbc` and `EntityFrameworkCore.Jet.OleDb`, that could then be discovered by `EntityFrameworkCore.Jet` at runtime.

**Comment by lauxjpn** [comment]
> For all advanced statements (like `CREATE VIEW` or `CREATE PROCEDURE`) to work with ODBC, `ExtendedAnsiSQL=1` has do be added to the connection string (see [Using the ExtendedAnsiSQL Connection String Attribute (Access Driver)](https://docs.microsoft.com/en-us/sql/odbc/microsoft/using-the-extendedansisql-connection-string-attribute-access-driver?view=sql-server-ver15) for further details).
> 
> We should do this implicitly in EFCore.Jet, so that nobody has to worry about it. In case anybody complains about it in the future for some reason, we can always add an option to disable it.

Implemented in 84aafe4 of #47.

**Comment by bubibubi** [comment]
I looked at the code. There are still square brackets around (at least in RemoveBrackets method). Probably we could just find **[** and replace (or, better, cover with tests because as far as I can understand all the tests work fine now).

**Comment by lauxjpn** [comment]
> I looked at the code. There are still square brackets around (at least in RemoveBrackets method). Probably we could just find **[** and replace (or, better, cover with tests because as far as I can understand all the tests work fine now).

Thanks, I missed a couple of those! I checked the `EFCore.Jet` and `System.Data.Jet` projects and fixed the remaining occurrences. (See 6141f1e of #47).

**Comment by bubibubi** [comment]
@lauxjpn WHAT A HUGE WORK!!! Great!!!

**Comment by bubibubi** [comment]
> They should all be running, but we are far away from having all the test green.

When you think that everything is stable enough tell me something because I'd like to help you on test fixing.

**Comment by lauxjpn** [comment]
The code should be stable enough after merging #47 (which I am going to do in a couple of hours). We currently have 1110 green, 788 red and 100 skipped tests from the `SimpleQueryJetTest` tests.
