### ISSUE TITLE
Unknown system table

### ISSUE THREAD

**Issue by ChrisJollyAU** [bubibubi/EntityFrameworkCore.Jet#56]
Using 3.1-preview branch

Trying to scaffold an .mdb database and it errors out without finishing the scaffolding

I'm getting "Unknown system table" for both ConstraintColumns and ForeignKeys

Is it possible to skip over/ignore those system tables?

**Comment by lauxjpn** [comment]
See https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/55#issuecomment-680160106
Please try again with once the PR has been merged.

**Comment by ChrisJollyAU** [comment]
Seems to be solved with that update you did. The classes are generated and the Foreign Keys and their navigation properties appear correctly.

Haven't tested if the navigation properties actually work yet

**Comment by ChrisJollyAU** [comment]
Navigation properties work as expected. Works fine to `Microsoft.EntityFrameworkCore.Proxies` for the lazy loading of the navigation properties

**Comment by lauxjpn** [comment]
I'll close this one then.
