### ISSUE TITLE
Scaffolding complex table indexes

### ISSUE THREAD

**Issue by ChrisJollyAU** [bubibubi/EntityFrameworkCore.Jet#57]
Using 3.1-preview

Is it possible to have a table with index over multiple columns?

So e.g. in code it would look like this

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Person>()
        .HasIndex(p => new { p.FirstName, p.LastName });
}

I appear to have a .mdb database that has something like this defined and scaffolding it is not working properly.

Digging deep into the indexes I have something like this
Table Name | Column Name | Index Name | Oridinal Position
TableA | Col1 | IndexName | 1
TableA | Col3 | IndexName | 2

So the scaffolding is putting an index on each of Col1 and Col3 with the name IndexName. So you end up having 2 indexes on the same table both with the same name. This causes an error when trying to run the program and access data

**Comment by lauxjpn** [comment]
See https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/55#issuecomment-680160106
Please try again once the PR has been merged.

**Comment by ChrisJollyAU** [comment]
I can confirm that the complex indexes are dealt with as expected
