### ISSUE TITLE
Scaffolding is converting to the wrong data type

### ISSUE THREAD

**Issue by ChrisJollyAU** [bubibubi/EntityFrameworkCore.Jet#58]
Using 3.1-preview branch and OleDb

My database has been scaffolding successfully however in the classes for the tables have the wrong data types. Fields that should be a datetime (and is shown as a Date/Time in Access) are actually scaffolded as a decimal. Other fields that are an integer are scaffolded as a boolean.

It looks like you matching against the wrong values in ConvertToJetDataType

For reference the following links list the ADO Data Types
https://www.w3schools.com/asp/ado_datatypes.asp
https://docs.microsoft.com/en-us/sql/ado/reference/ado-api/datatypeenum?view=sql-server-ver15

To use 2 of them as an example
A Date/Time field is adDate (value 7) - The value 7 with DbType is a decimal
An integer field is adInteger (value 3) - The value 3 with DbType is a boolean

The rest are also as different as the examples. Do note that I'm using it with OleDb, not sure if the values would be different if using Odbc

**Comment by lauxjpn** [comment]
See https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/55#issuecomment-680160106
Please try again once the PR has been merged.

**Comment by ChrisJollyAU** [comment]
Thanks. Will keep an eye out for the PR. I will note that I believe I have fixed/found a solution for the problems based on the current code

**Comment by ChrisJollyAU** [comment]
The updated bits scaffold the datatypes correctly
