### ISSUE TITLE
System.InvalidCastException: 'Object cannot be cast from DBNull to other types.'

### ISSUE THREAD

**Issue by ChrisJollyAU** [bubibubi/EntityFrameworkCore.Jet#61]
I'm getting this error when trying to access one of my tables from the DbContext

Stacktrace is

 	[External Code]	
 	System.Data.Jet.dll!System.Data.Jet.JetDataReader.GetDouble(int ordinal) Line 125	C#
 	[External Code]	
 	RMSync2.dll!RMSync2.Program.Main(string[] args) Line 23	C#

**Comment by lauxjpn** [comment]
Please post either the table's create statement or the mdb/accdb file.
Also post the model class (and any model definition like Fluent API if used) and the LINQ query you are trying to execute.

**Comment by ChrisJollyAU** [comment]
Further debugging. This is not a bug in the provider

All the columns in the table were defined as not nullable. Scaffolding agreed with that definition and the classes were fine.

However somehow or other (and I can't explain it either) for a single row 2 of the columns (a double and a bit) didn't have a value. Fixing it sorts the issue out

**Comment by lauxjpn** [comment]
Yeah, I reproduced it in the same way:

```c#
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class Cookie
    {
        public int CookieId { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Cookie> Cookies { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseJet("DBQ=Issue61.accdb") // ODBC
                //.UseJet("Data Source=Issue48.accdb") // OLE DB
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cookie>(
                entity =>
                {
                    entity.HasData(
                        new Cookie
                        {
                            CookieId = 1,
                            Name = "Free Sample",
                            Price = 1.00,
                        }
                    );
                });
        }
    }

    internal class Program
    {
        private static void Main()
        {
            // Create new database.
            using var context = new Context();
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var connection = context.Database.GetDbConnection();
            connection.Open();
            
            // Change table so that the `Price` column allows NULL values.
            // This will change the `Price` value of the "Free Sample" cookie to null.
            // Note, that our Cookie model class still assumes that `Price` cannot be null
            // (the property is still of type System.Double, not of type Nullable<System.Double>).
            using var command = connection.CreateCommand();
            command.CommandText = "ALTER TABLE `Cookies` DROP COLUMN `Price`";
            command.ExecuteNonQuery();
            command.CommandText = "ALTER TABLE `Cookies` ADD COLUMN `Price` double NULL";
            command.ExecuteNonQuery();

            var cookies = context.Cookies
                .ToList();

            Debug.Assert(cookies.Count == 2);
        }
    }
}
```

**Comment by ChrisJollyAU** [comment]
That would do it as well. I think in my case it was partially due to a recovered corrupt database. Was trying to compare 2 database to discover the differences.

Should there be any handling added to return a default value if it cant read the value?

**Comment by lauxjpn** [comment]
The provider will always assume a valid database that is in sync with the model definition. If the database schema or data is not what is expected, than neither the integrity of the database itself nor correct database operations on it by the application can be ensured anymore. Therefore throwing should already be the correct approach here.

**Comment by lauxjpn** [comment]
I did a check on how Access handles data violation cases. If you create a table with a nullable column `Price`, then insert some data that includes a `NULL` value for at least one of the `Price` values and later change the table schema for the `Price` column to be non-nullable, Access will show you the following prompt:

![image](https://user-images.githubusercontent.com/14178357/91549731-a89bca80-e927-11ea-84d2-c36a14a7741a.png)

So testing existing data against the new schema is optional. If you run the tests, then the following prompt will appear:

![image](https://user-images.githubusercontent.com/14178357/91549826-d8e36900-e927-11ea-90b6-edcb647baa5f.png)

So with clicking `No` on the first dialog or `Yes` on the second one, Access gives you two opportunities to just ignore data integrity violations and leave the table in an unexpected/invalid state.

If you later want to check the data integrity of your table, you can run the `Test Validation Rules` action from the `Tools` ribbon:

![image](https://user-images.githubusercontent.com/14178357/91550316-a8e89580-e928-11ea-9d43-9d51b6c66ee9.png)
![image](https://user-images.githubusercontent.com/14178357/91550387-c158b000-e928-11ea-90e7-dcad8a71519a.png)
![image](https://user-images.githubusercontent.com/14178357/91550459-dcc3bb00-e928-11ea-85ae-48eb03241021.png)

It would be nice to have a couple of utility functions at hand, where one of those functions would check the data integrity programmatically against the schema. While this is definitely technically possible, it would have a low priority on our TODO list at the moment.

**Comment by ChrisJollyAU** [comment]
A couple of things: 
 -Would it be worth adding an advanced option of something like `JetConfiguration.IgnoreDBNullConversionErrors = true;` That way you keep the normal behaviour but if you know what you're doing and acknowledge that you could have default values if it can't read the value. Basically saying give me what you can read

- Might have a look at doing that data integrity check. Could come in handy for me

- I could send you a sample mdb with the tables I've been testing on. Has around 78 tables and is an access '95 format. Would prefer to send privately

**Comment by lauxjpn** [comment]
> Would it be worth adding an advanced option of something like JetConfiguration.IgnoreDBNullConversionErrors = true; That way you keep the normal behaviour but if you know what you're doing and acknowledge that you could have default values if it can't read the value. Basically saying give me what you can read

I guess with Access actively allowing users to violate their data integrity, introducing an option to return a default value for an unexpected `DBNull` value (for non-nullable types) might be a good idea.

As a heads-up, for the `3.1.x` release we will remove the static `JetConfiguration` class and move its options to `JetConfiguration`, EFCore.Jet specific connection string options and `DbContextOptions`.

> I could send you a sample mdb with the tables I've been testing on. Has around 78 tables and is an access '95 format. Would prefer to send privately

Feel free to do so if you like and there are still issues to reproduce (see my profile page for an email address). I am however routinely migrating and maintaining Access apps to .NET, so I am using EFCore.Jet on multiple complex projects with a mix of many native Access and SQL Server liked tables, pass-through queries and procedures, so I have couple of real-word databases I can test features on.

I think we have no official statement on what database format versions are supported. However, the Access 95 format is very old, so there will be limitations to what it can actually support regarding EFCore.Jet (also depending on the used underlying driver/provider).

**Comment by ChrisJollyAU** [comment]
Finally got round to submitting the pull request to enable the setting
