### ISSUE TITLE
Using ToLower in a query throws IndexOutOfRange

### ISSUE THREAD

**Issue by Veflow** [bubibubi/EntityFrameworkCore.Jet#78]
Version: alpha 4

When using toLower(), I'm getting an IndexOutOfRange exception during query generation. When debugging the source, I found there was an issue in the JetStringMethodTranslator where the Trim clauses are formed. It checks if the passed arguments contain a null value on index 0, but it doesn't check if there actually is a value to begin with. That was the reason for the exception.

I've provided a proposed fix and some adjusted tests in PR #77

**Comment by lauxjpn** [comment]
@Veflow In contrast to what I wrote in my email, if you provide the detailed information as you have with your #77 PR, there is probably no need also open a corresponding issue, as long as the PR is only about bug fixes and not about introducing features!

**Comment by Veflow** [comment]
@lauxjpn Gotcha!
